/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ButtonSwitcher: typeof import('./components/ButtonSwitcher/ButtonSwitcher.vue')['default']
    Counter: typeof import('./components/Counter/Counter.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/Sidebar/Sidebar.vue')['default']
    UiButton: typeof import('./components/UiButton/UiButton.vue')['default']
    UiSearch: typeof import('./components/UiSearch/UiSearch.vue')['default']
    UserInfo: typeof import('./components/UserInfo/UserInfo.vue')['default']
    UserList: typeof import('./components/UserList/UserList.vue')['default']
    UserListItem: typeof import('./components/UserListItem/UserListItem.vue')['default']
  }
}
