/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ButtonSwitcher: typeof import('./components/ButtonSwitcher/ButtonSwitcher.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/Sidebar/Sidebar.vue')['default']
    UiSearch: typeof import('./components/UiSearch/UiSearch.vue')['default']
  }
}
