/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MarginRight: typeof import('./components/UiInput/margin-right.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiForm: typeof import('./components/UiForm/UiForm.vue')['default']
    UiInput: typeof import('./components/UiInput/UiInput.vue')['default']
    UiSelect: typeof import('./components/UiSelect/UiSelect.vue')['default']
  }
}
